# Generated by Django 3.1.7 on 2021-02-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_type', models.CharField(choices=[('imovel', 'imovel'), ('automovel', 'automovel'), ('empresa', 'empresa')], max_length=9)),
                ('description', models.TextField()),
                ('owner', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='LegalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('social_reason', models.CharField(max_length=200)),
                ('fantasy_name', models.CharField(max_length=200)),
                ('state_registration', models.CharField(max_length=12)),
                ('zipcode', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('owner', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
    ]
