openapi: '3.0.2'
info:
  title: API Pessoa fisica/juridica e bens
  version: '1.0'
  description: 'API REST utilizada para controlar o cadastro e consulta de pessoas físicas,
  pessoas jurídicas e seus proprietários bem como o registro de bens e posses
  associados às essas pessoas.'

servers:
  - url: https://localhost/v1
  - url: https://mytestenv.com/v1

paths:
  /physical-people:
    get:
      description: Consulta as informações da pessoa física com o CPF informado
      responses:
        '200':
          description: Lista de pessoas físicas cadastradas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PhysicalPerson'
    post:
      description: Cria um novo registro de pessoa física
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhysicalPerson'
            examples:
              PhysicalPersonAllFields:
                $ref: '#/components/examples/PhysicalPersonAllFields'
      responses:
        '201':
          description: Novo registro criado com sucesso
          content:
            application/json:
              examples:
                PhysicalPersonAllFields:
                  $ref: '#/components/examples/PhysicalPersonAllFields'

        '400':
          description: Parâmetros obrigatórios ausentes ou com valores inválidos
          content:
            application/json:
              example:
                {
                  "message": "Parâmetros faltando ou com valores inválidos"
                }

  /physical-people/{cpf}:
    parameters:
    - name: cpf
      in: path
      required: true
      description: Número do CFP sem pontos e traço e com 11 dígitos
      schema:
        type: string
    get:
      description: Consulta as informações da pessoa física com o CPF informado
      responses:
        '200':
          description: Dados da pessoa física pesquisada
          content:
            application/json:
              examples:
                PhysicalPersonAllFields:
                  $ref: '#/components/examples/PhysicalPersonAllFields'
        '404':
          description: Registro não encontrado
    put:
      description: Atualiza o registro da pessoa física com o CPF informado
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PhysicalPerson'
            examples:
              PhysicalPersonNoCPF:
                $ref: '#/components/examples/PhysicalPersonNoCPF'
      responses:
        '200':
          description: Registro atualizado com sucesso
        '400':
          description: Parâmetros obrigatórios ausentes ou com valores errados
          content:
            application/json:
              example:
                {
                  "message": "Parâmetros faltando ou com valores inválidos"
                }
    delete:
      description: Remove o registro da pessoa física com o CPF informado
      responses:
        '200':
          description: Registro removido com sucesso
        '404':
          description: Registro não encontrado

components:
  schemas:
    PhysicalPerson:
      type: object
      required:
        - cpf
        - name
        - zipcode
        - email
        - phone_number
      properties:
        cpf:
          type: string
          pattern: '^\d{11}$'
        name:
          type: string
          maxLength: 200
        zipcode:
          type: string
          pattern: '^\d{8}$'
        email:
          type: string
          maxLength: 255
        phone_number:
          type: string
          pattern: '^\d{10, 12}$'

    LegalPerson:
      type: object
      required:
        - cnpj
        - social_reason
        - fantasy_name
        - state_registration
        - owner
        - zipcode
        - email
        - phone_number
      properties:
        cnpj:
          type: string
          pattern: '^\d{14}$'
        social_reason:
          type: string
          minLength: 12
          maxLength: 200
        fantasy_name:
          type: string
          minLength: 12
          maxLength: 200
        state_registration:
          type: string
          pattern: '^\d{9, 12}$'
        owner:
          type: string
        zipcode:
          type: string
          pattern: '^\d{8}$'
        email:
          type: string
          maxLength: 255
        phone_number:
          type: string
          pattern: '^\d{10, 12}$'

    Goods:
      type: object
      required:
        - type
        - description
        - owner
      properties:
        type:
          type: string
          enum:
            - imovel
            - veiculo
            - empresa
        description:
          type: string
          maxLength: 300
        owner:
          type: string

  examples:
    PhysicalPersonAllFields:
      value:
        cpf: "25845675391"
        name: "Fulano Sem Sobrenome"
        zipcode: "11234567"
        email: "fulano@email.com"
        phone_number: "12345678912"

    PhysicalPersonNoCPF:
      value:
        name: "Fulano Sem Sobrenome"
        zipcode: "11234567"
        email: "fulano@email.com"
        phone_number: "12345678912"
